[package]
name = "carta-schema"
version = "0.1.0"
authors = ["Andrew Morcom"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
byteorder = "1.3.1"
log = "0.4.6"
failure = "0.1.5"
failure_derive = "0.1.5"
serde = "1.0"
serde_derive = "1.0"