# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/rust:1.35
    working_directory: ~/carta
    steps:
      - checkout
      - run: cargo test

workflows:
  version: 2
  build-and-coverage:
    jobs:
      - build_and_test
