# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/rust:1.31-node
    working_directory: ~/carta
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  coverage:
    docker:
      - image: circleci/rust:1.31-node
    environment:
      - RUSTFLAGS: -C link-dead-code
    working_directory: ~/carta
    steps:
      - checkout
      - run: cd native/carta-schema && cargo build
      - run: sudo apt-get install -y libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev
      - run: ./coverage.sh

workflows:
  version: 2
  build-and-coverage:
    jobs:
      - build_and_test
      - coverage:
          requires:
            - build_and_test
